name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Katalon Studio Github Action
        uses: katalon-studio/katalon-studio-github-action@v2
        with:
          version: '9.3.0'
          projectPath: '${{ github.workspace }}'
          args: >
            -noSplash
            -runMode=console
            -projectPath="${{ github.workspace }}/KatalonMobile/KatalonMobile.prj"
            -retry=0
            -testSuitePath="Test Suites/Run_TestSuite"
            -browserType="Android"
            -deviceId="${{secrets.deviceID}}"
            -executionProfile="default"
            -apiKey="${{secrets.KATALON_API_KEY}}"
            --config
            -proxy.auth.option=NO_PROXY
            -proxy.system.option=NO_PROXY
            -proxy.system.applyToDesiredCapabilities=true
            -webui.autoUpdateDrivers=true
            -appiumDirectory="/usr/local/lib/node_modules/appium"
            -consoleLog
